version: '3.7'

services:
  app:
    image: modulotechgroup/powerb2b:dev
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      URL: http://localhost:3000
    entrypoint: ./entrypoints/docker-entrypoint.sh

  redis:
    image: redis:6.2-alpine
